organization/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from organization.views import CreateOrganization, OrganizationList, OrganizationDetail, OrganizationEdit, \
    OrganizationViewSet
from django.contrib.auth import views as auth_view
app_name = 'organization'
router=DefaultRouter()
router.register('organization',OrganizationViewSet)
urlpatterns = [
    path('create/', CreateOrganization.as_view(), name='create'),
    path('all/',OrganizationList.as_view(),name='list'),
    path('detail/<int:pk>/',OrganizationDetail.as_view(),name='detail'),
    path('edit/<int:pk>/',OrganizationEdit.as_view(),name='edit'),
    path('api/',OrganizationViewSet.as_view())
]

organization/models.py
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _
from products.models import Product, Manufacture_Product
from organization.enums import OrganizationStatus

organization_phone_regex = RegexValidator(regex='^0[0-9]+$', message='invalid organization phone number')

mobile_phone_regex = RegexValidator(regex='^09[0-9]{9}$', message='invalid mobile phone number')


# organization model
class Organization(models.Model):
    province = models.CharField(verbose_name=_('province'), max_length=20)
    organization_name = models.CharField(max_length=50, verbose_name=_('organization name'))
    organization_phone = models.CharField(validators=[organization_phone_regex], max_length=11)
    workers = models.PositiveIntegerField(default=1, verbose_name=_('workers count'))
    production_crop = models.ManyToManyField(Manufacture_Product, related_name='product_entry',
                                             verbose_name=_('production crop'))
    contact_fullname = models.CharField(max_length=100, verbose_name=_('contact full name'))
    contact_mobile = models.CharField(validators=[mobile_phone_regex], verbose_name=_('contact mobile number'),
                                      max_length=11)
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    registrant_user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, verbose_name=_('registrant user'))
    status = models.CharField(choices=OrganizationStatus.choices, default=OrganizationStatus.in_progress, max_length=20)
    Followup = models.ForeignKey('sale.FollowUp', on_delete=models.PROTECT, verbose_name=_('Report'), null=True)

    # format time in created_date field
    def format_time(self):

        return self.created_date.strftime(format('%Y-%m-%d'))

    def __str__(self):
        return f'{self.organization_name} located in {self.province}'

organization/forms.py
from django import forms
from organization.models import Organization


# edit organization form
class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ('province', 'organization_name', 'organization_phone',
                  'workers', 'production_crop', 'contact_fullname', 'contact_mobile',
                  'email')
        widgets = {
            'email': forms.EmailInput,
            'workers':forms.NumberInput
        }

organization/views.py
import datetime
import logging
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from rest_framework import permissions
from rest_framework.authentication import BasicAuthentication, SessionAuthentication
from rest_framework.generics import ListAPIView
from sale.models import FollowUp
from products.models import Manufacture_Product
from organization.models import Organization
from organization.forms import OrganizationForm
from organization.serializer import OrganizationSerializer
from organization.permission import IsOwnerOrReadOnly

logger = logging.getLogger(__name__)


@method_decorator(csrf_exempt, name='dispatch')
class CreateOrganization(LoginRequiredMixin, CreateView):
    """
    create organization view
    """
    template_name = 'organization/create.html'
    form_class = OrganizationForm
    success_url = reverse_lazy('organization:list')

    def form_valid(self, form):
        # set user by request.user
        form.instance.registrant_user = self.request.user
        logger.info(msg=f'{self.request.user.username} create new organization')
        super(CreateOrganization, self).form_valid(form)
        return redirect('organization:list')

    def form_invalid(self, form):
        logger.error(msg=f'{self.request.user.username} entered invalid input for form')
        messages.error(request=self.request, message='your inputs for this form in invalid check it again!')
        return super(CreateOrganization, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        # formatted date for using in template
        kwargs['date'] = datetime.datetime.now().strftime(format('%Y-%m-%d'))
        # getting user for using in template
        kwargs['registrant_contact'] = self.request.user.username
        return super(CreateOrganization, self).get_context_data(**kwargs)


class OrganizationList(LoginRequiredMixin, ListView):
    """
    list all organization that self user created
    """
    template_name = 'organization/list.html'
    paginate_by = 3

    # only organization created by request.user
    def get_queryset(self):
        logger.info(msg='loading organization models successfully')
        return Organization.objects.filter(registrant_user=self.request.user)


# detail of each organization
class OrganizationDetail(LoginRequiredMixin, DetailView):
    template_name = 'organization/detail.html'
    model = Organization

    def get(self, request, *args, **kwargs):
        return super(OrganizationDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # all products
        kwargs['all_products'] = list(
            map((lambda x: x[1]), list(Manufacture_Product.objects.values_list())))
        # Manufacture_Product.objects.filter()
        # all products except own organizations
        kwargs['reports'] = FollowUp.objects.all()[:3]
        products_tags = set(
            map(lambda x: x.tags.values_list('id', flat=True), self.object.production_crop.all()))
        #  change recommended via tags
        try:
            kwargs['recommended'] = list(
                map((lambda x: x[1]), list(Manufacture_Product.objects.filter(tags__in=products_tags).exclude(
                    pk=kwargs['object'].id).values_list())))
        except TypeError:
            kwargs['recommended'] = ''
        # pk user
        kwargs['pk'] = self.object.registrant_user.pk
        return super(OrganizationDetail, self).get_context_data(**kwargs)


class OrganizationEdit(LoginRequiredMixin, UpdateView):
    """
    Edit each organization
    """
    template_name = 'organization/edit.html'
    model = Organization
    fields = ('province', 'organization_name', 'organization_phone',
              'workers', 'contact_fullname',
              'contact_mobile', 'email', 'status')
    success_url = reverse_lazy('organization:list')

    def get_object(self, queryset=None):
        return super(OrganizationEdit, self).get_object(queryset)


class OrganizationViewSet(LoginRequiredMixin, ListAPIView):
    queryset = Organization.objects.all()
    serializer_class = OrganizationSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    authentication_classes = [SessionAuthentication, BasicAuthentication]

organization/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script rel="script" src="{% static 'js/jQuery.js' %}"></script>
    <style>
        body {
            background-color: beige;
        }
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        li {
            float: left;
        }
        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover:not(.active) {
            background-color: #111;
        }
    </style>
    {% block style %}{% endblock %}
</head>
<body>
<ul id="nav">
    <li><a href="{% url 'login' %}">Log in</a></li>
    <li><a href="{% url 'organization:list' %}">Organization</a></li>
    <li><a href="{% url 'admin:products_product_changelist' %}">Product</a></li>
    <li><a href="{% url 'sale:list' %}">Sale</a></li>
</ul>
{% block body %}{% endblock %}
{% block script %}{% endblock %}
</body>
</html>

organization/templates/organization/create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Create new organization 🏢{% endblock %}
{% block style %}
    <style>
        a{
            width: 60px;
            height: 60px;
            background: aqua;
            border-radius: 5px;
            padding: 5px;
            text-decoration: none;
            margin: 10px;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row bg-info">
            <h1 class="display-4 text-center">Register new organization</h1>
        </div>
        <div class="container mt-3">
            <form method="post">
                <div class="row">
                    <div class="col-6">
                        {{ form.province|add_class:'form-control'|attr:'placeholder:Province' }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {{ form.organization_name|add_class:'form-control'|attr:'placeholder:Organization name' }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {{ form.organization_phone|add_class:'form-control'|attr:'placeholder:Phone' }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {{ form.workers|add_class:'form-control'|attr:'placeholder:workers' }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {{ form.production_crop }}<a href="{% url 'admin:products_manufacture_product_add' %}">+</a>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {{ form.contact_fullname|add_class:'form-control'|attr:'placeholder:contact fullname' }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {{ form.contact_mobile|add_class:'form-control'|attr:'placeholder:contact mobile phone' }}
                    </div>
                    <div class="col-6">
                        {{ form.email|add_class:'form-control'|attr:'placeholder:contact email' }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                    <label for="date">Date of Registration</label>
                        <input id="date" value="{{ date }}" class="form-control" disabled>
                    </div>
                    <div class="col-6">
                    <label for="registrant_contact">Registrant Contact</label>
                        <input id="registrant_contact" value="{{ registrant_contact }}" class="form-control" disabled>
                    </div>
                </div>
                <div class="row mt-3">
                    <button class="btn btn-primary col-12" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

organization/templates/organization/detail.html
{% extends 'base.html' %}
{% block title %}Organization detail{% endblock %}
{% block body %}
    <p class="display-4 text-center bg-primary">Details of {{ object.organization_name }} organization</p>
    <div class="container">
        <div class="btn-group btn-group-lg mb-2">
            <div><a href="{% url 'organization:list' %}" class="btn btn-primary">Back</a></div>
            <div><a href="#" class="btn btn-warning">Invoice issuance</a></div>
            <div><a href="{% url 'organization:edit' object.pk %}" class="btn btn-success">Edit</a></div>
        </div>
        <div class="row">
            <div class="col-4">
                <label for="province">Province: </label>
                <input type="text" id="province" disabled value="{{ object.province }}">
            </div>
            <div class="col-4">
                <label for="phone">Organization phone: </label>
                <input type="text" id="phone" disabled value="{{ object.organization_phone }}">
            </div>
            <div class="col-4">
                <label for="date">Registration Date: </label>
                <input type="text" id="date" disabled value="{{ object.format_time }}">
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-4">
                <label for="workers">Workers: </label>
                <input type="text" id="workers" disabled value="{{ object.workers }}">
            </div>
            <div class="col-4">
                <label for="registrar">Registrar: </label>
                <input type="text" id="registrar" data-pk="{{ pk }}"
                       disabled value="{{ object.registrant_user }}">
            </div>
        </div>
        <div class="row mt-4">
            <label>Products:
                <input type="text" disabled value="{{ all_products|join:', ' }}">
            </label>
        </div>
        <div class="row mt-4">
            <label>Recommended Products:
                {% if recommended %}
                    <input type="text" disabled value="{{ recommended|join:', ' }}">
                {% else %}
                    <input type="text" disabled value="No suggestion">
                {% endif %}
            </label>
        </div>
        <div class="row mt-4">
            <div class="col-6">
                <label>contact fullname:
                    <input type="text" disabled value="{{ object.contact_fullname }}">
                </label>
            </div>
            <div class="col-6">
                <label>contact mobile phone:
                    <input type="tel" disabled value="{{ object.contact_mobile }}">
                </label>
            </div>
        </div>
        <hr>
        <div class="row-mt-4">
            <div class="invisible alert" id="status"></div>
            <h3 class="display-4" style="text-align: center">Report History</h3>
            {% if reports %}
                <table class="table table-stripped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>User</th>
                        <th>Date</th>
                        <th>Report</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for report in reports %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td id="user" data-pk="{{ report.pk }}">{{ report.user.username }}</td>
                            <td>{{ report.date }}</td>
                            <td><a class="btn btn-primary" href="{% url 'sale:report_detail' report.pk %}">Detail</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h2 class="text-center">No Report exist</h2>
            {% endif %}
        </div>
        <div class="row mt-2">
            <textarea id="work-report" name="report" cols="15" rows="10" placeholder="report"></textarea>
            <button class="btn btn-primary mt-2" id="save-btn">Save</button>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(
            $('#save-btn').click(function () {
                const report = $('#work-report').val();
                debugger;
                const date = new Date();
                const user_pk = $('#registrar')[0].dataset.pk;
                let cookie = document.cookie
                const csrf = cookie.substring(cookie.indexOf('=') + 1)
                $.ajax({
                    url: '{% url "sale:save report" %}',
                    data: {
                        report: report,
                        date: date,
                        user_pk: user_pk
                    },
                    headers: {
                    'X-CSRFToken': csrf
                    },
                    method: 'POST',
                    success: function (response) {
                        const context='<span class="closebtn">&times;</span>'+
                            '<strong>Success!</strong> '+response.message;
                        $('#status').removeClass('invisible').addClass('success').append(context);
                    },
                    error: function (response) {
                        const context='<span class="closebtn">&times;</span>'+
                            '<strong>Error!</strong> '+response.message;
                        $('#status').removeClass('invisible').append(context);
                    }
                })
            })
        );
    </script>
{% endblock %}

organization/templates/organization/edit.html
{% extends 'base.html' %}
{% block title %}Edit {{ object.organization_name }} organization{% endblock %}
{% block body %}
        <h3 class="text-center display-3">Edit form 📝</h3>
        <form method="post" class="container was-validated">
            {% csrf_token %}
            <div class="form-row justify-content-center d-flex">
                <div class="form-group col-4 m-4">
                    {% with field=form.organization_name %}
                        <label>Organization name:
                            <input type="text" value="{{ field.initial }}" name="{{ field.name }}">
                        </label>
                    {% endwith %}
                </div>
                <div class="form-group col-4 m-4">
                    {% with field=form.organization_phone %}
                        <label>Organization phone:
                            <input type="text" value="{{ field.initial }}" name="{{ field.name }}" required
                                   pattern="^09[0-9]+$">
                            <div class="valid-feedback">Valid email</div>
                            <div class="invalid-feedback">invalid feedback</div>
                        </label>
                    {% endwith %}
                </div>
                <div class="form-row col-4 m-4">
                    {% with field=form.province %}
                        <label>Province:
                            <input type="text" value="{{ field.initial }}" name="{{ field.name }}">
                        </label>
                    {% endwith %}
                </div>
            </div>
            <div class="form-row mt-3 justify-content-center d-flex">
                <div class="form-group col-6 m-4">
                    <label>workers :
                        <input type="number" value="{{ form.workers.initial }}" name="{{ form.workers.name }}">
                    </label>
                </div>
                <div class="form-group col-6 m-4">
                    {% with field=form.email %}
                        <label>Email :
                            <input type="email" value="{{ field.initial }}" name="{{ field.name }}">
                            <div class="valid-feedback">Valid email</div>
                            <div class="invalid-feedback">invalid feedback</div>
                        </label>
                    {% endwith %}
                </div>
            </div>
            <div class="form-row mt-3 justify-content-center d-flex">
                <div class="form-group col-4 m-4">
                    {% with field=form.contact_fullname %}
                        <label>
                            Contact fullname:
                            <input type="text" value="{{ field.initial }}" name="{{ field.name }}">
                        </label>
                    {% endwith %}
                </div>
                <div class="form-group col-5 m-4">
                    {% with field=form.contact_mobile %}
                        <label>
                            Contact mobile phone:
                            <input type="number" pattern="^09[0-9]{9}$"
                                   value="{{ field.initial }}" name="{{ field.name }}">
                        </label>
                    {% endwith %}
                </div>
                <div class="form-group col-3 m-4">
                    {% with field=form.status %}
                        <label>
                            Status:
                            <select name="{{ field.name }}">
                                {% for item in field.subwidgets %}
                                    <option value="{{ item.name }}">{{ item.name }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    {% endwith %}
                </div>
            </div>
            <div class="form-row justify-content-center d-flex">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>

{% endblock %}

organization/templates/organization/list.html
{% extends 'base.html' %}
{% block title %}all organizations{% endblock %}
{% block body %}
    <h2 class="text-center">Organization list</h2>
    <div class="clearfix m-2">
        <a href="{% url 'organization:create' %}" class="btn btn-primary float-end">Create organization</a>
    </div>
    <table class="table table-dark bg-dark">
        <thead>
        <tr>
            <th class="col-1">#</th>
            <th class="col-3">Organization name</th>
            <th class="col-3">Registrar</th>
            <th class="col-3">Contact</th>
            <th class="col-2">Status</th>
        </tr>
        </thead>
        {% for organization in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'organization:detail' organization.pk %}">{{ organization.organization_name }}</a>
                </td>
                <td>{{ organization.registrant_user }}</td>
                <td>{{ organization.contact_fullname }}</td>
                <td>{{ organization.status }}</td>
            </tr>
        {% endfor %}
    </table>
    <div class="justify-content-center d-flex">
        {% include 'organization/pagination.html' %}
    </div>
{% endblock %}

organization/templates/organization/pagination.html
{% if page_obj.has_previous %}
    <a href="{{ request.path }}?page=1" class="page-link btn">First</a>
    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="page-link btn">&laquo;</a>
{% else %}
    <a href="{{ request.path }}?page=1" class="page-link btn">First</a>
{% endif %}
<li class="page-item active"><a class="page-link btn">{{ page_obj.number }}</a></li>
{% if page_obj.has_next %}
    <a class="page-link btn" href="{{ request.path }}?page={{ page_obj.next_page_number }}">&raquo;</a>
    <a class="page-link btn" href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}