sale/urls.py
from django.urls import path
from sale.views import CreateQuote, QuoteList, PrintOrder, save_report, Email_send, Report_detail

app_name = 'sale'
urlpatterns = [
    path('create/', CreateQuote.as_view(), name='create'),
    path('list/',QuoteList.as_view(),name='list'),
    path('print/<int:pk>/',PrintOrder.as_view(),name='print'),
    path('report/<int:pk>/',Report_detail.as_view(),name='report_detail'),
    path('save/',save_report,name='save report'),
    path('email/<int:pk>/',Email_send.as_view(),name='email')
    # path('email/',email_order,name='email')
]

sale/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import F, Sum, Count
from django.urls import reverse
from django.utils.functional import cached_property
from organization.models import Organization
from products.models import Product
from django.utils.translation import ugettext_lazy as _


class QuoteItem(models.Model):
    device = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name=_('Device'))
    quantity = models.PositiveIntegerField(default=1, verbose_name=_('Device quantity'))
    price = models.PositiveBigIntegerField(verbose_name=_('device price'))
    discount = models.FloatField(default=0, verbose_name=_('Device discount'))
    quote = models.ForeignKey('sale.Quote', on_delete=models.CASCADE, null=True)

    @cached_property
    def get_price(self):
        if self.device.taxable:
            total_without_discount = self.quantity * self.price * 1.09
            return self.discount * total_without_discount
        else:
            return self.discount * self.quantity * self.price

    def __str__(self):
        return f'Quote Item with total price {self.price * self.quantity}'


class Quote(models.Model):
    """
    Quote model fields
    """
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, null=True)
    quote_date = models.DateTimeField(verbose_name=_('Quote date'), auto_now=True)

    def __str__(self):
        return f'{self.organization} quote'

    @cached_property
    def get_total_price(self):
        return self.quoteitem_set.annotate(total=F('price') * F('quantity')).aggregate(Sum('total'))['total__sum']

    @cached_property
    def get_total_count(self):
        return self.quoteitem_set.aggregate(Count('quantity'))['quantity__count']


class FollowUp(models.Model):
    """
    Follow up model
    """
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, verbose_name=_('user'))
    date = models.DateTimeField(verbose_name=_('Date'), auto_now=True)
    report = models.TextField(verbose_name=_('report'))

    class Meta:
        ordering=('-date',)

    def __str__(self):
        return f'The report created in {self.date} by {self.user}'

    @cached_property
    def format_time(self):
        return self.date.strftime('%Y-%m-%d')

    def get_absolute_url(self):
        return reverse('sale:report detail', args=[self.pk])


class EmailHistory(models.Model):
    email = models.EmailField(verbose_name=_('receiver email'))
    success = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)

    def __str__(self):
        return f'Email sent to {self.email} successfully' if self.success else f"Email doesn't sent to {self.email}"

sale/forms.py
from django import forms
from sale.models import FollowUp
from products.models import Product
from organization.models import Organization


class QuoteItemForm(forms.Form):
    organ=forms.ModelChoiceField(queryset=Organization.objects.all(),initial='')
    device=forms.ModelChoiceField(queryset=Product.objects.all())
    quantity=forms.IntegerField()
    price=forms.IntegerField()
    discount=forms.FloatField()


class ReportForm(forms.ModelForm):
    class Meta:
        model=FollowUp
        fields=('user','report')

sale/views.py
import datetime
import json
from smtplib import SMTPException
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST

from my_signal import email_signal
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import FormView, ListView, DetailView
from sale.models import Quote, FollowUp, QuoteItem
from products.models import Product
from sale.forms import QuoteItemForm, ReportForm
from organization.models import Organization
import weasyprint
from sale.celery_tasks import send_mail_to


class CreateQuote(LoginRequiredMixin, FormView):
    form_class = QuoteItemForm
    template_name = 'sale/create.html'
    """
    Create Quote class based view 
    """
    def get_context_data(self, **kwargs):
        kwargs['products'] = Product.objects.all().values_list()
        kwargs['organizations'] = Organization.objects.all().values_list()
        return super(CreateQuote, self).get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        content = request.POST.get('contents', None)
        data = json.loads(content)
        quote = Quote.objects.create(organization_id=int(data[0]['organizationId']), quote_date=datetime.datetime.now())
        for item in data:
            QuoteItem.objects.create(device_id=int(item['deviceId']), quantity=int(item['quantity']),
                                     price=int(item['price']), discount=float(item['discount']) / 100.0,
                                     quote_id=quote.pk)
        return JsonResponse(data={'message': 'Quote saved successfully'}, status=200)


class QuoteList(LoginRequiredMixin, ListView):
    paginate_by = 3
    template_name = 'sale/list.html'
    model = Quote
    """
    list quote items class based view 
    """


class PrintOrder(LoginRequiredMixin, DetailView):
    model = Quote
    """
    get pdf output file of quote
    """
    def get(self, request, *args, **kwargs):
        g = super(PrintOrder, self).get(request, *args, **kwargs)
        rendered_content = g.rendered_content
        pdf = weasyprint.HTML(string=rendered_content).write_pdf()
        response = HttpResponse(pdf, content_type='application/pdf')
        return response


# describe each report
class Report_detail(LoginRequiredMixin,DetailView):
    template_name = 'sale/detail_report.html'

    def get_object(self, queryset=None):
        return FollowUp.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        kwargs['report']=self.get_object()
        return super(Report_detail, self).get_context_data(**kwargs)

@require_POST
def save_report(request):
    """
    save report on organization page
    """
    report = request.POST.get('report', None)
    user_pk = int(request.POST.get('user_pk', None))
    user = User.objects.get(pk=user_pk)
    form_instance = ReportForm({'user': user, 'date': datetime.datetime.now(), 'report': report})
    if form_instance.is_valid():
        form_instance.save()
        return JsonResponse(data={'status': 'ok', 'message': 'Report saved successfully'}, status=200)
    else:
        return JsonResponse(data={'status': 'error', 'message': "Report doesn't saved successfully"}, status=400)


# sending email by class based view
class Email_send(LoginRequiredMixin, DetailView):
    def get(self, request, *args, **kwargs):
        quote = Quote.objects.get(pk=kwargs['pk'])
        organization_email = quote.organization.email
        quotes = quote.quoteitem_set.all()
        try:
            send_mail_to('CRM Email', 'sale/email.html', organization_email, quotes)
            email_signal.send(sender=Quote, instance=quote, success=True)
            messages.info(request, 'email sent!')
        except SMTPException:
            email_signal.send(sender=Quote, instance=quote, success=False)
        return redirect('sale:list')

sale/templates/sale/create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Create Quote{% endblock %}
{% block body %}
    <div class="container">
        <h3 class="display-4 bg-warning text-center">Create new Quote</h3>
        <div class="row mt-4 col-6">
            <label for="id_organ">Organization name:</label>
            <select name="organ" id="id_organ">{% for organization in organizations %}
                <option value="{{ organization.0 }}">{{ organization.2 }}</option>
            {% endfor %}
            </select>
        </div>
        <div class="row mt-4">
            <p class="text-center display-3">Required devices</p>
        </div>
        <div class="row mt-4">
            <table class="table table-dark bg-dark">
                <thead>
                <tr>
                    <th>Discount</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Device</th>
                </tr>
                </thead>
                <tbody id="table_body">
                <tr>
                    <td>{{ form.discount|attr:'placeholder:discount'|attr:'disabled' }}</td>
                    <td>{{ form.price|attr:'placeholder:price'|attr:'disabled' }}</td>
                    <td>{{ form.quantity|attr:'placeholder:quantity'|attr:'disabled' }}</td>
                    <td>
                        <label>Devices
                            <select name="device" class="Device" data-pk="1">
                                {% for product in products %}
                                    <option onclick="show(this)" value="{{ product.0 }}"
                                            data-price="{{ product.2 }}">{{ product.1 }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="alert alert-success invisible" id="success"></div>
        </div>
        <div class="row mt-4">
            <a class="col-4 btn btn-secondary" href="{% url 'sale:list' %}">🔙 Back</a>
            <button class="btn btn-success col-4" id="save">Save 💾</button>
            <button id='add' onclick="Add()" class="btn btn-primary text-center col-4">Add ➕</button>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $('#save').click(function () {
            {# set whole items in array #}
            let contents = []
            const all_quotes = $('#table_body').children();
            const organizationId = $('#id_organ').find(':selected')[0].value;
            for (let i = 0; i < all_quotes.length; i++) {
                if (!all_quotes[i].children[0].hasAttribute('disabled')) {
                    const discount = all_quotes[i].children[0].children[0].value;
                    const price = all_quotes[i].children[1].children[0].value;
                    const quantity = all_quotes[i].children[2].children[0].value;
                    const deviceId = all_quotes[i].children[3].children[0].children[0].dataset.pk;
                    contents.push({
                        'discount': discount, 'price': price, 'quantity': quantity,
                        'deviceId': deviceId, 'organizationId': organizationId
                    })
                }
            }
            let cookie = document.cookie
            const csrf = cookie.substring(cookie.indexOf('=') + 1)
            const dataString = JSON.stringify(contents)
            $.ajax({
                url: '{% url "sale:create" %}',
                data: {contents: dataString},
                headers: {
                    'X-CSRFToken': csrf
                },
                method: 'POST',
                success: function (response) {
                    $('#success').removeClass('invisible').css('text-align','center').html(response.message);
                }
            })
        });

        function show(event) {
            const price=event.dataset.price;
            const specific_row = $(event).parent().parent().parent().parent();
            specific_row[0].children[0].children[0].removeAttribute('disabled');
            specific_row[0].children[0].children[0].value = 0;
            specific_row[0].children[1].children[0].removeAttribute('disabled');
            specific_row[0].children[1].children[0].value = price;
            specific_row[0].children[2].children[0].removeAttribute('disabled');
            specific_row[0].children[2].children[0].value = 1;
            $(event).parent()[0].dataset.pk = $(event)[0].value;
        }

        let options = $('.Device').children();
        let StringOptions = '';
        for (let i = 0; i < options.length; i++) {
            StringOptions += options[i].outerHTML;
        }

        function Add() {
            const content = '<tr>' +
                '<td><input type="number" name="discount" step="any" disabled placeholder="discount" required id="id_discount"></td>' +
                '<td><input type="number" name="price" disabled placeholder="price" required id="id_price"></td>' +
                '<td><input type="number" name="quantity" disabled placeholder="quantity" required id="id_quantity"></td>' +
                '<td>' +
                '<label>Devices' +
                '<select name="device" class="Device">' +
                StringOptions +
                '</select></label>' +
                '</td>' +
                '</tr>';
            $('#table_body').append(content);
        }
    </script>
{% endblock %}

sale/templates/sale/detail_report.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ report }}{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
    <div class="container">
    <h2 class="text-center display-3 text-info">Detail</h2>
    <div class="row mt-2">
        <div class="col-6">
            <label>User
            <input disabled value="{{ report.user.username }}">
            </label>
        </div>
        <div class="col-6">
            <label>Date
            <input disabled value="{{ report.format_time }}">
            </label>
        </div>
    </div>
    <div class="mt-4" style="padding: 25px">
        Report Context:
        <pre style="border: 2px solid orangered">
            {{ report.report }}
        </pre>
    </div>
    <div class="row">
        <a class="btn btn-info" href="{% url 'organization:list' %}">Back</a>
    </div>
    </div>
{% endblock %}

sale/templates/sale/email.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Content</title>
    <link rel="stylesheet" href="{% static 'css/pdf.css' %}">
</head>
<body>
<h2 style="color: red; margin: auto">Your quote contains these items</h2>
{% if quotes %}
    <table class="table">
    <thead>
        <tr>
            <th>device</th>
            <th>price</th>
            <th>quantity</th>
            <th>total</th>
        </tr>
    </thead>
        {% for item in quotes.quoteitem_set.all %}
            <tr>
                <td>{{ item.device }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.total }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p id="not">No content exist</p>
{% endif %}
</body>
</html>

sale/templates/sale/list.html
{% extends 'base.html' %}
{% block title %}Quote List{% endblock %}
{% block body %}
    <div class="container">
        <div class="row mb-2">
            <h2 class="display-3 text-center">Quote List</h2>
        </div>
        <a href="{% url 'sale:create' %}" class="col-3 btn btn-primary align-right">Create quote</a>
        <table class="table table-stripped">
            <thead>
            <tr>
                <th>#</th>
                <th>Customer name</th>
                <th>Devices</th>
                <th>Output PDF</th>
                <th>Operation (email)📧</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ object.organization.contact_fullname }}</td>
                    <td>{% for item in object.quoteitem_set.all %}{{ item.device|join:', ' }}{% endfor %}</td>
                    <td><a href="{% url 'sale:print' object.pk %}">Download pdf</a></td>
                    <td><a href="{% url 'sale:email' object.pk %}">Email 📨</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="justify-content-center d-flex">
            {% include 'organization/pagination.html' %}
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success text-center">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

sale/templates/sale/quote_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Quote List {{ quote.organization.organization_name }}</title>
        <style>
            .price{
                width: 50%;
                background-color: bisque;
                float: left;
                text-align: center;
            }
            .count{
                width: 50%;
                background-color: aliceblue;
                float: left;
                text-align: center;
            }
            body{
                padding: 20px;
            }
            table,th,td{
               border-collapse: collapse;
               border: 2px solid black;
               text-align: center;
            }
            thead{
                background-color: aqua;
            }
            #quote tr:nth-child(even){
                background-color: aliceblue;
            }
            #quote tr:nth-child(odd){
                background-color: #978686;
            }
            h2{
                font-size: xx-large;
                color: red;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <h2>Quote List {{ quote.organization.organization_name }} company</h2>
        <table style="width: 100%">
            <thead>
                <tr style="border-collapse: collapse" >
                <th style="border: 2px solid black;border-collapse: collapse">#</th>
                <th style="border: 2px solid black;border-collapse: collapse">Device</th>
                <th style="border: 2px solid black;border-collapse: collapse">quantity</th>
                <th style="border: 2px solid black;border-collapse: collapse">Price</th>
                </tr>
            </thead>
            <tbody id="quote">
                {% for item in quote.quoteitem_set.all %}
                    <tr class="head_site">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.device }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.price }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="total_values" style="margin-top: 20px">
            <div class="price">
                <p>Total Price: <span style="color: red">{{ quote.get_total_price }}$</span></p>
            </div>
            <div class="count">
                <p>Total Quantity of quote: {{ quote.get_total_count }}</p>
            </div>
        </div>
    </body>
</html>